version: "{build}"

platform: x64
clone_folder: c:\gopath\src\bitfx
branches:
  only:
    - master

skip_tags: true

environment:
  GOPATH: c:\gopath
  GOVERSION: 1.6

install:
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - rmdir c:\go /s /q
  - appveyor DownloadFile https://storage.googleapis.com/golang/go%GOVERSION%.windows-amd64.zip
  - 7z x go%GOVERSION%.windows-amd64.zip -y -oC:\ > NUL
  - go version
  - go env
#  - go get github.com/thrasher-/gocryptotrader
  - ps: cd c:\gopath\src\bitfx\bitarb

artifacts:
  - path: "fx.exe"
    name: bitfx
build_script:
  - go get
  - go build

after_build:
 # - ps: cp ../../../../bin/*.exe fx.exe
  - ps: ls
test: off
deploy: off
